app:
  jwt:
    access-token-expiration-ms: 900000
    refresh-token-expiration-ms: 604800000
    secret: 'test-secret'

  oauth:
    authorized-redirect-uri: http://localhost:5173/auth/callback

  cors:
    allowed-origins:
      - http://localhost:5173